# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765e4232740778eaf20f01d3096df45b803c9c006a8b10ce7d3f0105e188756f215d3a36ef044259467367767de34786db79f2e8bee55b3af1bf4e65c47b4fd8

test:
  secret_key_base: d95b2d0a2d46502dcbca4efd9f0bb1ea54e982038d47db81a0d632047c7110406d0d0c5ac214e0636d2f2aca35e179633ea1206e613cf3aa91046e37303194a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
